### ISSUE TITLE
Repository with the history

### ISSUE THREAD

**Issue by aaferrari** [necrose99/abeni-reborn#4]
Hello Michael, checking the commits I saw that you had problems migrating the old CVS repository, so I decided to try the same thing with [this command](http://ghantoos.org/2010/11/11/migrating-sourceforge-cvs-source-repository-to-github/#comment-8739) and you can see the results in https://github.com/aaferrari/abeni-git Keep in mind that this repository differs from yours in the following:
* I had to add [this commit](https://github.com/aaferrari/abeni-git/commit/c3088d34eb4e9f2133c032482f041acd7b07bbfe) to maintain consistency with your subsequent modifications.
* The .wxg files are kept in the wxglade folder, I keep the original ChangeLog as well as the files fx.png, stop.png and x.png.
* To avoid having redundant code [I converted the qt-abeni folder into a branch](https://github.com/aaferrari/abeni-git/tree/qt-abeni).
* The folder sf.net-cvs-srcs and the files `#~wxg.autosave~GetURIDialog.xml#`, `#~wxg.autosave~GetURIDialog.xml# `and `#~wxg.autosave~GetURIDialog.xml#` were not included, but you can add it if you wish.

Also add an additional commit to make the program work with WxPython 3. At the moment I am not doing much with Abeni but someday I plan to work with some ideas that I have in mind.

**Comment by necrose99** [comment]
feel free to pull req  , I'll merge them...

this tool depends on YE olden wxpython, (wxpython has since become incompatible in newer versions)   was tinkering with a qt port as qt ui tends to have pointers if they depreciate items... 

this tool , had some definite potential , but it needs love/  bountysource etc. 
ebuilds are as much of an art as a science..   devs get , but admins first starting to do them can wring their hair out figuring out were they screwed up.  the IDE , would help on that end...

**Comment by aaferrari** [comment]
>feel free to pull req , I'll merge them...

The problem is that since it is a repository with a different history, when I try to pull a request, the following appears:
>### There isn’t anything to compare.
>**necrose99:master** and **aaferrari:master** are entirely different commit histories.

And I did not find how to force a pull request so a way to solve it would be to clone abeni-git on your machine and then overwrite the repository with the following command:
`git push --force --repo https://github.com/necrose99/abeni-reborn`
Although you may want to make a copy of the original repository first (for example, by [duplicating](https://help.github.com/articles/duplicating-a-repository/) it, renaming it to something like "abeni-reborn-old" and perhaps [archiving](https://help.github.com/articles/about-archiving-repositories/) it).
>was tinkering with a qt port as qt ui tends to have pointers if they depreciate items...

One of the ideas that I have in mind is to completely separate the graphical interface from the rest of the code to make it easier to integrate into any graphical toolkit (or maybe even make a ncurses version) but I don't have much free time to do this these days. If you want to know more about it, [aMSN2](http://www.amsn-project.net/forums/index.php?board=15.0) had this modular approach and Pidgin has something similar with [libpurple](https://developer.pidgin.im/wiki/WhatIsLibpurple).
>this tool , had some definite potential , but it needs love/ bountysource etc.

I agree, I have updated/modified some ebuilds before (such as [FreeBASIC](https://bugs.gentoo.org/96711#c16), [wxGlade](https://bugs.gentoo.org/530004#c10) or [Launchy](https://bugs.gentoo.org/647374) in QT5) and I think with some improvements Abeni could simplify certain things (and not only me, but also others who want to install programs in Gentoo).

**Comment by necrose99** [comment]
rebase will do.

**Comment by necrose99** [comment]
https://github.com/aaferrari/abeni-git  rebase merge . item done.
